services:
  bot:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/finbot_db
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ping:1})"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
